config/routes.rb
Rails.application.routes.draw do
  devise_for :customers


  devise_scope :customer do  
    get '/customers/sign_out' => 'devise/sessions#destroy'     
  end
  get 'home/index'
  get 'article/home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #root "article#home"

  root "home#index"

  resources :article
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user


end    

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles

    validates :username, presence: true,uniqueness: true
    validates :email, presence: true,uniqueness: true
end    

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
  before_action :authenticate_customer!#internal method
  #if customer is not logged in-->display the login page
  def home
  end


  #Read operation
  #-->read all articles(index)#/article
  #-->read particular article(show)#/article/id

  def show
    #byebug
    @article=Article.find(params[:id])#params[:id]=2
  end  


  def index
    @articles=Article.paginate(page: params[:page], per_page: 3)
  end

  #Create operation(inserting the data)
  #-->new
  #-->create


  def new
    @article=Article.new

  end
  
  
  def create
    #byebug
    @article=Article.new(params.require(:article).permit(:title,:description,:user_id))
    @article.save()
    redirect_to article_index_path
  
  end


  #Update operation:
  #-->edit
  #-->update

  def edit
    @article=Article.find(params[:id])#title=django,description=middleware

  end


  def update
    @article=Article.find(params[:id])#old title and old description
    @article.update(params.require(:article).permit(:title,:description))#new title and new desc
    @article.save()
    redirect_to article_index_path

    #olddata.update(newdata)
  end  


  def destroy
    @article=Article.find(params[:id])
    @article.delete()
    redirect_to article_index_path

  end  






















end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/article/edit.html.erb
<h1>Editing Article</h1>


<%= form_with(model: @article, local: true) do |f| %>

    <%= f.label :Title %>
    <%= f.text_field :title  %><br><br>

    <%= f.label :Description %>
    <%= f.text_area :description  %><br><br>


    <%= f.submit  %>
    
<% end %>    



  

app/views/article/home.html.erb
<h1>Home</h1>

app/views/article/index.html.erb
<%= image_tag("picture/book.jpg") %>

<%= will_paginate @articles %>

<% @articles.each do |i| %>
<div class="card">
  <div class="card-header">
    By <%= i.user.username %>
  </div>

  <div class="card-body">
    <h5 class="card-title">Title:<%= i.title %></h5>
    <p class="card-text">Description:<%= i.description %></p>
    <%= link_to 'Delete', article_path(i.id),method: :delete,class: "btn btn-outline-danger" %>
  </div>
  
</div>
<% end %>

app/views/article/new.html.erb
<h1>Article Creation Form</h1>




<%= form_with scope: :article, url: article_index_path, local: true do |f| %>


    <%= f.label :Title %>
    <%= f.text_field :title  %><br><br>

    <%= f.label :Description %>
    <%= f.text_area :description  %><br><br>

    <%= f.label :User_id %>
    <%= f.text_field :user_id  %><br><br>



    <%= f.submit  %>



    
<% end %>    

app/views/article/show.html.erb
<h1>Showing Article Details</h1>


<h1>Title:<%= @article.title  %></h1>
<h1>Title:<%= @article.description  %></h1>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fifth</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">CRUD APP</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <li class="nav-item">
        <%= link_to 'View Articles', article_index_path, class: "nav-link" %>
      </li>
      
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <% if customer_signed_in? %>
          <%= link_to 'logout',destroy_customer_session_path,class: "dropdown-item" %>
        <% else %>
            <%= link_to 'Login',customer_session_path,class: "dropdown-item" %>
            <%= link_to 'Signup',new_customer_registration_path,class: "dropdown-item" %>
        <% end %>
          </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<div class="container" align="center">

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
    <%= yield %>
</div>    

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>